---
abstract: 'Perl DNS resolver module'
author:
  - 'Olaf Kolkman <olaf@net-dns.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-DNS
no_index:
  directory:
    - t
    - inc
requires:
  Digest::HMAC: 1.01
  Digest::MD5: 2.13
  Digest::SHA: 5.23
  IO::Socket: 1.24
  MIME::Base64: 2.11
  Test::More: 0.52
  perl: 5.00404
version: 0.77_2
