--- #YAML:1.0
name:               Net-DNS
version:            0.75
abstract:           Perl DNS resolver module
author:
    - Olaf Kolkman <olaf@net-dns.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::HMAC:  1.01
    Digest::MD5:   2.13
    Digest::SHA:   5.23
    IO::Socket:    1.24
    MIME::Base64:  2.11
    perl:          5.00404
    Test::More:    0.52
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
